BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mydistro"
BBFILE_PATTERN_mydistro = "^${LAYERDIR}/"
BBFILE_PRIORITY_mydistro = "10"

LAYERSERIES_COMPAT_mydistro = "kirkstone"
